### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by LeiiY** [hysts/pl_gaze_estimation#1]
hello,thx 4 ur great work,could u kindly provide the pretrained model？my email is yanglei204@mails.ucas.edu.cn  I promise not to share this model with others

**Comment by hysts** [comment]
Hi, @LeiiY 

Pretrained models are provided [here](https://github.com/hysts/pytorch_mpiigaze_demo/releases/tag/v0.1.0) and [here](https://github.com/hysts/pytorch_mpiigaze_demo/releases/tag/v0.2.2).
